name: web_front
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^3.1.3
  connectivity_plus: ^2.0.3
  dartz: ^0.10.0
  desktop_drop: ^0.2.0
  dio: ^4.0.4
  dotted_border: ^2.0.0+1
  file_picker: ^4.2.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.0
  font_awesome_flutter: ^9.2.0
  freezed_annotation: ^1.0.0
  http: ^0.13.4
  http_mock_adapter: ^0.3.2
  json_annotation: ^4.3.0
  widgetbook: ^1.0.1
  widgetbook_annotation: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.4
  auto_route_generator: ^3.1.0
  freezed: ^1.0.0
  json_serializable: ^6.0.1
  widgetbook_generator: ^1.0.1
  mockito: ^5.0.15
  

flutter:
  uses-material-design: true
