// Mocks generated by Mockito 5.0.16 from annotations
// in web/test/features/upload/domain/use_case/fetch_latest_info_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:web/core/error/failures.dart' as _i5;
import 'package:web/features/upload/domain/entity/app_version.dart' as _i6;
import 'package:web/features/upload/domain/repository/i_app_version_repository.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [IAppVersionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAppVersionRepository extends _i1.Mock
    implements _i3.IAppVersionRepository {
  MockIAppVersionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AppVersion>> fetchLatestInfo() =>
      (super.noSuchMethod(Invocation.method(#fetchLatestInfo, []),
          returnValue: Future<_i2.Either<_i5.Failure, _i6.AppVersion>>.value(
              _FakeEither_0<_i5.Failure, _i6.AppVersion>())) as _i4
          .Future<_i2.Either<_i5.Failure, _i6.AppVersion>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> saveAppVersion(
          _i6.AppVersion? newVerison) =>
      (super.noSuchMethod(Invocation.method(#saveAppVersion, [newVerison]),
              returnValue: Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                  _FakeEither_0<_i5.Failure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
  @override
  String toString() => super.toString();
}
