@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjdjZjYzNWE3LWZlMGItNDgyNi1iNGQ0LTlkYjAzYzYwZWRkZCIsImF1dGhvcml6ZWQiOnRydWUsImV4cGlyYXRpb24iOjE2MjU4MTc2MTQsInVzZXJfaWQiOiIxIn0.8NPzNfCSfgPO0b5gF3-OEV1DsfREBo8j12lo81UwVSA
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmF0aW9uIjoxNjI2NDIxNTE0LCJyZWZyZXNoX3V1aWQiOiI4MjI5YTBjYS0yZTZiLTQ1YzgtYmNlMS1kMWJhZDA3ZTAwN2UiLCJ1c2VyX2lkIjoiMSJ9.BnF2C5PEnjOaly5ehKqmQOQpCk-_djlGh5K2e8Ov9pc

# OAuth 응답은 다음과 같이 넘어옴
# {"accessToken":"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","refreshToken":null,"idToken":null,"tokenEndpoint":"https://github.com/login/oauth/access_token","scopes":["read:user,repo"],"expiration":null}

###
GET http://localhost:8080/data HTTP/2.0

###
POST http://localhost:8080/sign-in HTTP/2.0
content-type: application/json 

{
	"id": "dev",
	"pwd": "dev"
}
###
POST http://localhost:8080/todo HTTP/2.0
content-type: application/json 
Authorization: bearer {{accessToken}}

{
	"title": "test todo"
}
###
DELETE http://localhost:8080/sign-out HTTP/2.0
content-type: application/json 
Authorization: bearer {{accessToken}}

{

}
###
POST http://localhost:8080/proto HTTP/2.0
content-type: application/json 

{
  "COMP_CD": "3000"
}
###
