###
GET http://localhost:9110/data HTTP/2.0

###
POST http://localhost:9110/sign-in HTTP/2.0
content-type: application/json 

{
	"userId": "dev",
	"pwd": "dev",
  "compCd":"3000",
  "sysFlag":"MOBILE"
}
###
POST http://localhost:9110/todo HTTP/2.0
content-type: application/json 

{
	"title": "test todo"
}
###
POST http://localhost:9110/proto HTTP/2.0
content-type: application/json 

{
  "COMP_CD": "3000"
}
###

GET http://localhost:9110/norm?comp-cd=3000&obj-flag=BUILDING HTTP/2.0
content-type: application/json 

###
GET http://localhost:9110/gubun?comp-cd=3000&sys-flag=MOBILE&user=dev&flag=FORKLIFT HTTP/2.0
content-type: application/json

###
GET http://localhost:9110/info?comp-cd=3000&sys-flag=MOBILE&user=dev&check-no=33F1CC18 HTTP/2.0
content-type: application/json

###

