## nested freezed data class 를 만들 때 
## nested 하게 만들어지지 않는 상황이 발생할 수 있음
## 이는 code generation할 때, 따로 설정하지 않았기 때문임

## 반드시 이 파일의 configuration을 다음과 같이 설정해야함
targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      freezed:
        options:
          union_key: type
          union_value_case: pascal