name: web
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  freezed_annotation: ^1.0.0
  path_provider: ^2.0.7
  path: ^1.8.0
  auto_route: ^3.2.0
  json_annotation: ^4.4.0
  connectivity_plus: ^2.1.0
  desktop_drop: ^0.2.0
  cross_file: ^0.3.2
  dio: ^4.0.4
  file_picker: ^4.2.7


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2
  hooks_riverpod: ^1.0.2
  flutter_hooks: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.2.0
  freezed: ^1.0.2
  json_serializable: ^6.1.1
  build_runner: ^2.1.5
  mockito: ^5.0.16
  flutter_lints: ^1.0.4
  http_mock_adapter: ^0.3.2
  flutter_gen_runner: ^4.1.3

flutter_gen:
  output: lib/core/gen/
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/

  fonts:
    - family: GmarketSans
      fonts:
        - asset: assets/fonts/GmarketSansBold.otf
        - asset: assets/fonts/GmarketSansLight.otf
        - asset: assets/fonts/GmarketSansMedium.otf
  